name: Build images

on:
  workflow_dispatch:

jobs:
  build_base:
    name: Build base
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu]
        tag: [jammy,kinetic]
        include:
          - image: debian
            tag: sid
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
        with:
          version: latest
          driver-opts: image=moby/buildkit:master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Image Name
        id: imagename
        run: echo "::set-output name=name::ghcr.io/${GITHUB_REPOSITORY,,}/${{ matrix.image }}-${{ matrix.tag }}:latest"

      - name: Build base image
        uses: docker/build-push-action@v3
        with:
          context: images/base
          push: true
          cache-from: type=registry,ref=${{ steps.imagename.outputs.name }}
          cache-to: type=inline
          tags: ${{ steps.imagename.outputs.name }}
          build-args: |
            image=${{ matrix.image }}
            tag=${{ matrix.tag }}

  build_target_bases:
    name: Build target base
    needs: build_base
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu]
        tag: [jammy,kinetic]
        platform: [win32]
        include:
          - image: debian
            tag: sid
            platform: win32
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
        with:
          version: latest
          driver-opts: image=moby/buildkit:master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Image Name
        id: imagename
        run: echo "::set-output name=name::ghcr.io/${GITHUB_REPOSITORY,,}/${{ matrix.image }}-${{ matrix.tag }}-${{ matrix.platform }}:latest"

      - name: Build target base image
        uses: docker/build-push-action@v3
        with:
          context: images/base-${{ matrix.platform }}
          push: true
          cache-from: type=registry,ref=${{ steps.imagename.outputs.name }}
          cache-to: type=inline
          tags: ${{ steps.imagename.outputs.name }}
          build-args: |
            image=${{ matrix.image }}
            tag=${{ matrix.tag }}
